-- Hut edit approval workflow
-- Instructors submit proposed Hut changes for approval.
-- Approvers, admins and superadmins may approve/reject; admins/superadmins may delete.

create table if not exists public.hut_change_requests (
  id bigint generated by default as identity primary key,
  hut_id bigint not null references public.huts(id) on delete cascade,
  requested_by uuid not null references auth.users(id),
  requested_at timestamptz not null default now(),
  proposed_data jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  review_comment text
);

create index if not exists hut_change_requests_status_idx
  on public.hut_change_requests (status);

create index if not exists hut_change_requests_hut_id_idx
  on public.hut_change_requests (hut_id);

alter table public.hut_change_requests enable row level security;

grant select, insert, update on table public.hut_change_requests to authenticated;

create policy "Authenticated users can read hut change requests"
  on public.hut_change_requests
  for select
  to authenticated
  using (true);

create policy "Instructors can submit hut changes"
  on public.hut_change_requests
  for insert
  to authenticated
  with check (
    requested_by = (select auth.uid())
    and exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('instructor', 'approver', 'admin', 'superadmin')
    )
  );

create policy "Approvers can review hut changes"
  on public.hut_change_requests
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver', 'admin', 'superadmin')
    )
  )
  with check (
    status in ('approved', 'rejected')
    and reviewed_by = (select auth.uid())
  );

-- The function performs the Hut update and request review atomically.
-- It deliberately checks the caller's profile role inside the database.
create or replace function public.review_hut_change_request(
  request_id bigint,
  decision text,
  comment text default null
)
returns public.hut_change_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  reviewer_role text;
  request_row public.hut_change_requests;
  updated_request public.hut_change_requests;
begin
  select role into reviewer_role
  from public.profiles
  where id = auth.uid();

  if reviewer_role not in ('approver', 'admin', 'superadmin') then
    raise exception 'Only approvers and admins can review Hut changes';
  end if;

  if decision not in ('approved', 'rejected') then
    raise exception 'Invalid Hut change decision';
  end if;

  select *
  into request_row
  from public.hut_change_requests
  where id = request_id
    and status = 'pending'
  for update;

  if not found then
    raise exception 'Pending Hut change request not found';
  end if;

  if decision = 'approved' then
    update public.huts h
    set
      name = p.name,
      alternative_names = p.alternative_names,
      country = p.country,
      region = p.region,
      latitude = p.latitude,
      longitude = p.longitude,
      elevation_m = p.elevation_m,
      summer_access = p.summer_access,
      winter_access = p.winter_access,
      approach_routes = p.approach_routes,
      typical_approach_time = p.typical_approach_time,
      approach_difficulty = p.approach_difficulty,
      seasonal_restrictions = p.seasonal_restrictions,
      sleeping_capacity = p.sleeping_capacity,
      winter_room = p.winter_room,
      food_and_meals = p.food_and_meals,
      picnic_lunches = p.picnic_lunches,
      water = p.water,
      water_drinkable = p.water_drinkable,
      toilets = p.toilets,
      showers = p.showers,
      electricity = p.electricity,
      wifi = p.wifi,
      cooking = p.cooking,
      blankets_mattresses = p.blankets_mattresses,
      booking_required = p.booking_required,
      booking_url = p.booking_url,
      phone = p.phone,
      email = p.email,
      vendor = p.vendor,
      vendor_status_expires_at = p.vendor_status_expires_at,
      guide_rate_offered = p.guide_rate_offered,
      guardian_name = p.guardian_name,
      guardian_email = p.guardian_email,
      guardian_phone = p.guardian_phone,
      max_capacity = p.max_capacity,
      emergency_information = p.emergency_information,
      nearby_hazards = p.nearby_hazards,
      useful_route_information = p.useful_route_information,
      instructor_notes = p.instructor_notes,
      photos = p.photos,
      last_checked_at = p.last_checked_at,
      last_checked_by = p.last_checked_by,
      source = p.source,
      updated_at = now(),
      updated_by = (select name from public.profiles where id = auth.uid())
    from jsonb_to_record(request_row.proposed_data) as p(
      name text,
      alternative_names text[],
      country text,
      region text,
      latitude double precision,
      longitude double precision,
      elevation_m integer,
      summer_access text,
      winter_access text,
      approach_routes text,
      typical_approach_time text,
      approach_difficulty text,
      seasonal_restrictions text,
      sleeping_capacity integer,
      winter_room text,
      food_and_meals text,
      picnic_lunches boolean,
      water text,
      water_drinkable boolean,
      toilets text,
      showers text,
      electricity text,
      wifi text,
      cooking text,
      blankets_mattresses text,
      booking_required boolean,
      booking_url text,
      phone text,
      email text,
      vendor boolean,
      vendor_status_expires_at date,
      guide_rate_offered boolean,
      guardian_name text,
      guardian_email text,
      guardian_phone text,
      max_capacity integer,
      emergency_information text,
      nearby_hazards text,
      useful_route_information text,
      instructor_notes text,
      photos text[],
      last_checked_at timestamptz,
      last_checked_by text,
      source text
    )
    where h.id = request_row.hut_id;

    if not found then
      raise exception 'Hut record not found';
    end if;
  end if;

  update public.hut_change_requests
  set
    status = decision,
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    review_comment = comment
  where id = request_row.id
  returning * into updated_request;

  return updated_request;
end;
$$;

revoke all on function public.review_hut_change_request(bigint, text, text) from public, anon;
grant execute on function public.review_hut_change_request(bigint, text, text) to authenticated;

-- Replace the original broad Hut update policy. Direct updates are reserved for
-- approvers/admins; instructors must use hut_change_requests instead.
drop policy if exists "Content editors can update huts" on public.huts;

create policy "Approvers and admins can update huts"
  on public.huts
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver', 'admin', 'superadmin')
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver', 'admin', 'superadmin')
    )
  );

drop policy if exists "Content editors can create huts" on public.huts;

create policy "Approvers and admins can create huts"
  on public.huts
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver', 'admin', 'superadmin')
    )
  );


-- Hut records are special: only admins/superadmins may approve deletion
-- requests for Hut knowledge points. Approvers may not delete Huts.
create or replace function public.approve_guide_note_deletion(
  request_id bigint,
  review_comment text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  request_record public.guide_note_deletion_requests%rowtype;
  user_role text;
  note_category text;
begin
  select p.role
    into user_role
  from public.profiles p
  where p.id = auth.uid();

  if user_role not in ('approver', 'admin', 'superadmin') then
    raise exception 'You are not authorised to approve deletion requests';
  end if;

  select *
    into request_record
  from public.guide_note_deletion_requests
  where id = request_id
    and status = 'pending'
  for update;

  if not found then
    raise exception 'Deletion request not found or already reviewed';
  end if;

  select category
    into note_category
  from public.guide_notes
  where id = request_record.guide_note_id;

  if lower(coalesce(note_category, '')) = 'hut'
     and user_role not in ('admin', 'superadmin') then
    raise exception 'Only admins can delete Huts';
  end if;

  if request_record.guide_note_id is not null then
    delete from public.guide_notes
    where id = request_record.guide_note_id;
  end if;

  update public.guide_note_deletion_requests
  set status = 'approved',
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      review_comment = approve_guide_note_deletion.review_comment
  where id = request_id;

  update public.guide_note_deletion_requests
  set status = 'rejected',
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      review_comment = 'Superseded by approval of another deletion request.'
  where guide_note_id = request_record.guide_note_id
    and id <> request_id
    and status = 'pending';
end;
$$;
