-- Hut database foundation
-- Apply only when the Hut Database feature is ready for a Supabase environment.

create table if not exists public.huts (
  id bigint generated by default as identity primary key,
  guide_note_id bigint not null unique references public.guide_notes(id) on delete cascade,

  name text not null,
  alternative_names text[],

  country text,
  region text,
  latitude double precision,
  longitude double precision,
  elevation_m integer,

  summer_access text,
  winter_access text,
  approach_routes text,
  typical_approach_time text,
  approach_difficulty text,
  seasonal_restrictions text,

  sleeping_capacity integer,
  winter_room text,
  food_and_meals text,
  water text,
  toilets text,
  showers text,
  electricity text,
  wifi text,
  cooking text,
  blankets_mattresses text,

  booking_required boolean,
  booking_url text,
  phone text,
  email text,

  school_group_suitable boolean,
  group_capacity integer,
  staff_leader_considerations text,
  emergency_information text,
  nearby_hazards text,
  useful_route_information text,
  instructor_notes text,

  photos text[],

  last_checked_at timestamptz,
  last_checked_by text,
  source text,
  updated_at timestamptz not null default now(),
  updated_by text,

  created_at timestamptz not null default now(),
  created_by text
);

create index if not exists huts_name_idx on public.huts (name);
create index if not exists huts_region_idx on public.huts (region);
create index if not exists huts_country_idx on public.huts (country);

alter table public.huts enable row level security;

-- Authenticated users can read hut records.
create policy "Authenticated users can read huts"
  on public.huts
  for select
  to authenticated
  using (true);

-- Creation/editing/deletion should be restricted to the app's management roles.
-- These policies will be aligned with the existing role model before the
-- migration is applied to Supabase.
