create table if not exists public.huts (
  id bigint generated by default as identity primary key,
  guide_note_id bigint not null unique references public.guide_notes(id) on delete cascade,
  name text not null,
  alternative_names text[],
  country text,
  region text,
  latitude double precision,
  longitude double precision,
  elevation_m integer,
  summer_access text,
  winter_access text,
  approach_routes text,
  typical_approach_time text,
  approach_difficulty text,
  seasonal_restrictions text,
  sleeping_capacity integer,
  winter_room text,
  food_and_meals text,
  picnic_lunches boolean,
  water text,
  water_drinkable boolean,
  toilets text,
  showers text,
  electricity text,
  wifi text,
  cooking text,
  blankets_mattresses text,
  booking_required boolean,
  booking_url text,
  phone text,
  email text,
  vendor boolean,
  vendor_status_expires_at date,
  guide_rate_offered boolean,
  guardian_name text,
  guardian_email text,
  guardian_phone text,
  max_capacity integer,
  emergency_information text,
  nearby_hazards text,
  useful_route_information text,
  instructor_notes text,
  photos text[],
  last_checked_at timestamptz,
  last_checked_by text,
  source text,
  updated_at timestamptz not null default now(),
  updated_by text,
  created_at timestamptz not null default now(),
  created_by text
);

create index if not exists huts_name_idx on public.huts (name);
create index if not exists huts_region_idx on public.huts (region);
create index if not exists huts_country_idx on public.huts (country);

alter table public.huts enable row level security;
grant select, insert, update, delete on table public.huts to authenticated;

create policy "Authenticated users can read huts"
  on public.huts for select to authenticated using (true);

create policy "Content editors can create huts"
  on public.huts for insert to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver','admin','superadmin')
    )
  );

create policy "Content editors can update huts"
  on public.huts for update to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver','admin','superadmin')
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('approver','admin','superadmin')
    )
  );

create policy "Admins can delete huts"
  on public.huts for delete to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = (select auth.uid())
        and profiles.role in ('admin','superadmin')
    )
  );

insert into public.huts (
  guide_note_id,name,latitude,longitude,picnic_lunches,water,water_drinkable,guide_rate_offered
)
select id,title,latitude,longitude,true,
       'Not drinkable; bottled water must be purchased.',
       false,
       case when lower(title) = 'cabane rambert' then true else false end
from public.guide_notes
where lower(category) = 'hut'
  and title in ('Cabane de la Tourche','Cabane Rambert','Cabane Fenestral','Cabane du Demècre')
on conflict (guide_note_id) do nothing;